/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.lab5;

import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
public class PalindromeExampleTest {
    @Test
    public void testPositiveCases() {
        final List<String> postiveList = Arrays.asList(null, "", "x", "aaa", "hannah", "did",
                "radar", "mom", "dad", "noon", "civic", "radar", "my gym", "top spot",
                "was it a cat I saw");

        for (String testStr : postiveList) {
            boolean isPalindrome = PalindromeExample.isPalindrome(testStr);
            Assert.assertTrue("'" + testStr + "' should be palindrome", isPalindrome);
        }
    }

    @Test
    public void testNegativeCases() {
        boolean isPalindrome = PalindromeExample.isPalindrome("my gym is");
        Assert.assertFalse("'my gym is' should not be palindrome", isPalindrome);
    }
}
